# Generated by Django 5.2.17 on 2026-09-16 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('doc', 'Document'), ('mail', 'Mail')], default='doc', max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('preview', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='passon.collaborator')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('collaborator', 'reference'), name='unique_item_per_collaborator')],
            },
        ),
    ]
