# Generated by Django 5.2.17 on 2026-09-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passon', '0002_collaboratoritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratoritem',
            name='author_email',
            field=models.CharField(blank=True, max_length=320),
        ),
    ]
