# Generated by Django 5.2.17 on 2026-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passon', '0003_collaboratoritem_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='avatar_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
