# Generated by Django 5.2.17 on 2026-09-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    """Mail is gone, so an item can only be a document.

    Choices only, no data migration: every row was already "doc". The
    snapshot is replaced on every read of someone's own items, and nothing
    has produced a mail row since the Messages connector was removed.
    """

    dependencies = [
        ('passon', '0004_collaborator_avatar_collaborator_avatar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratoritem',
            name='kind',
            field=models.CharField(choices=[('doc', 'Document')], default='doc', max_length=20),
        ),
    ]
